export const classNames = {
  levelInfo: 'level-info',
  levelInfoHidden: 'hidden',
  row: 'level-info__row',
  levelNumber: 'level-info__level-number',
  title: 'level-info__title',
  subtitle: 'level-info__subtitle',
  selector: 'level-info__selector',
  description: 'level-info__description',
  example: 'level-info__example',
  levelChangers: 'level-changers',
  levelChangersPrev: 'level-changers__prev',
  levelChangersNext: 'level-changers__next',
  levelInfoState: 'level-info__state',
  levelCompleted: 'completed',
  levelHelped: 'help-used',
  checkmarkIcon: 'checkmark-icon',
  helpIcon: 'help-icon',
  levelInfoToggle: 'level-info__toggle',
};
